version: '3'

services:
  database:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      DB_NAME: market
    volumes:
      - database_data:/var/lib/postgresql/data:rw

  redis:
    image: redis

  app:
    build: Dockerfile
    volumes:
      - .:/var/www/html

  nginx:
    image: nginx
    ports:
      - "83:80"
    volumes:
      - ./apps/platform/build/nginx/default.conf:/etc/nginx/templates/default.conf.template

volumes:
  database_data:
